/**
 * setup-env.js
 * Quick setup script to create .env.local with Supabase credentials
 * Run: node setup-env.js
 */
const fs = require('fs');
const path = require('path');

// Known Supabase URL from your app
const SUPABASE_URL = 'https://wunqntfreyezylvbzvxc.supabase.co';

console.log('🔧 MONZA TECH ENVIRONMENT SETUP');
console.log('================================');
console.log('');
console.log('✅ Found your Supabase URL:', SUPABASE_URL);
console.log('');
console.log('❓ YOU NEED 2 MORE CREDENTIALS:');
console.log('');
console.log('1️⃣ ANON KEY (public key):');
console.log('   Go to: https://supabase.com/dashboard/project/wunqntfreyezylvbzvxc/settings/api');
console.log('   Copy the "anon/public" key');
console.log('');
console.log('2️⃣ SERVICE ROLE KEY (private key):');
console.log('   Copy the "service_role" key from the same page');
console.log('   ⚠️  KEEP THIS SECRET - never expose in frontend');
console.log('');

// Get input from user
const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('📝 Enter your credentials below:');
console.log('');

rl.question('🔑 Paste your ANON KEY: ', (anonKey) => {
  rl.question('🔐 Paste your SERVICE_ROLE KEY: ', (serviceKey) => {
    
    const envContent = `# Monza Tech Supabase Configuration
# Auto-generated by setup-env.js

# Public API URL
VITE_SUPABASE_URL=${SUPABASE_URL}

# Public anon key (safe for frontend)
VITE_SUPABASE_ANON_KEY=${anonKey}

# Service role key (PRIVATE - for uploads only)
VITE_SUPABASE_SERVICE_ROLE_KEY=${serviceKey}

# Generated on: ${new Date().toISOString()}
`;

    // Write .env.local file
    const envPath = path.join(__dirname, '.env.local');
    
    try {
      fs.writeFileSync(envPath, envContent);
      
      console.log('');
      console.log('🎉 SUCCESS! Environment file created!');
      console.log('');
      console.log('✅ Created: .env.local');
      console.log('✅ Configured: VITE_SUPABASE_URL');
      console.log('✅ Configured: VITE_SUPABASE_ANON_KEY'); 
      console.log('✅ Configured: VITE_SUPABASE_SERVICE_ROLE_KEY');
      console.log('');
      console.log('🚀 READY TO UPLOAD YOUR 107 CARS!');
      console.log('');
      console.log('Next steps:');
      console.log('1. npm run upload:monza-inventory');
      console.log('2. Refresh your car inventory page');
      console.log('3. See all vehicles displayed!');
      console.log('');
      
    } catch (error) {
      console.error('❌ Failed to create .env.local:', error.message);
      console.log('');
      console.log('📋 MANUAL SETUP:');
      console.log('Create a file called .env.local and add:');
      console.log('');
      console.log(envContent);
    }
    
    rl.close();
  });
});
