import { Car } from './types';

export const carInventoryData: Car[] = [
  // VOYAH VEHICLES
  {
    id: '1',
    model: 'Voyah Free',
    year: 2024,
    color: 'Pearl White',
    arrivalDate: '2024-03-15',
    soldDate: '2024-04-20',
    status: 'sold',
    vinNumber: 'VYH24FR87629A1',
    currentFloor: 'Inventory',
    batteryPercentage: 95,
    pdiCompleted: true,
    pdiTechnician: 'John Smith',
    pdiDate: '2024-03-16',
    pdiNotes: 'All systems checked, minor paint touch-up completed',
    brand: 'Voyah',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 52000,
    clientName: 'Ahmed Al-Rashid',
    clientPhone: '+971-50-123-4567',
    clientEmail: 'ahmed.rashid@email.com',
    clientAddress: 'Dubai Marina, UAE',
    lastUpdated: '2024-04-20T10:30:00Z',
    softwareVersion: '2.3.1',
    softwareLastUpdated: '2024-04-15T09:00:00Z',
    softwareUpdateBy: 'IT-Ahmed',
    softwareUpdateNotes: 'Latest infotainment system update'
  },
  {
    id: '2',
    model: 'Voyah Dream',
    year: 2025,
    color: 'Midnight Blue',
    arrivalDate: '2024-04-05',
    status: 'in_stock',
    vinNumber: 'VYH25DR24971B3',
    currentFloor: 'Showroom 1',
    batteryPercentage: 87,
    pdiCompleted: true,
    pdiTechnician: 'Sarah Johnson',
    pdiDate: '2024-04-06',
    pdiNotes: 'Perfect condition, ready for display',
    brand: 'Voyah',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 62000,
    inShowroom: true,
    showroomEntryDate: '2024-04-07',
    lastUpdated: '2024-06-15T14:22:00Z',
    testDriveHistory: [
      {
        isOnTestDrive: false,
        testDriveStartTime: '2024-06-10T10:00:00Z',
        testDriveEndTime: '2024-06-10T10:30:00Z',
        testDriveDuration: 30,
        testDriverName: 'Mohammed Hassan',
        testDriverPhone: '+971-55-987-6543',
        testDriverLicense: 'DL123456789',
        notes: 'Interested in features, checking acceleration',
        isClientTestDrive: true
      }
    ],
    softwareVersion: '2.4.0',
    softwareLastUpdated: '2024-06-10T14:00:00Z',
    softwareUpdateBy: 'IT-Sarah',
    softwareUpdateNotes: 'Updated to latest version with enhanced battery management'
  },
  {
    id: '3',
    model: 'Voyah Passion',
    year: 2024,
    color: 'Silver Frost',
    arrivalDate: '2024-05-10',
    status: 'reserved',
    vinNumber: 'VYH24PS12345D7',
    currentFloor: 'Showroom 2',
    batteryPercentage: 78,
    pdiCompleted: true,
    pdiTechnician: 'Lisa Wang',
    pdiDate: '2024-05-11',
    pdiNotes: 'Small paint scratch noted and repaired',
    brand: 'Voyah',
    category: 'REV',
    customs: 'paid',
    sellingPrice: 55000,
    clientName: 'Omar Al-Mansouri',
    clientPhone: '+971-56-777-8888',
    clientEmail: 'omar.mansouri@email.com',
    clientAddress: 'Sharjah, UAE',
    reservedDate: '2024-05-15',
    inShowroom: true,
    showroomEntryDate: '2024-05-12',
    lastUpdated: '2024-05-15T11:15:00Z',
    damages: [
      {
        id: 'damage_1',
        description: 'Minor paint scratch on rear bumper',
        severity: 'minor',
        location: 'Rear bumper, left side',
        timestamp: '2024-05-10T14:30:00Z'
      }
    ]
  },
  {
    id: '4',
    model: 'Voyah Free',
    year: 2025,
    color: 'Obsidian Black',
    arrivalDate: '2024-05-12',
    status: 'in_stock',
    vinNumber: 'VYH25FR67890E2',
    currentFloor: 'New Arrivals',
    batteryPercentage: 82,
    pdiCompleted: false,
    brand: 'Voyah',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 54000,
    notes: 'Recently arrived, awaiting PDI inspection',
    lastUpdated: '2024-05-12T08:30:00Z',
    softwareVersion: '1.8.5',
    softwareLastUpdated: '2024-03-20T10:00:00Z',
    softwareUpdateBy: 'IT-Mohamed',
    softwareUpdateNotes: 'Initial software installation'
  },
  {
    id: '5',
    model: 'Voyah Dream',
    year: 2024,
    color: 'Ocean Teal',
    arrivalDate: '2024-03-22',
    soldDate: '2024-04-25',
    status: 'sold',
    vinNumber: 'VYH24DR13579H8',
    currentFloor: 'Inventory',
    batteryPercentage: 94,
    pdiCompleted: true,
    pdiTechnician: 'Robert Kim',
    pdiDate: '2024-03-23',
    pdiNotes: 'Perfect condition, premium package confirmed',
    brand: 'Voyah',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 63000,
    clientName: 'Aisha Al-Qahtani',
    clientPhone: '+971-54-222-3333',
    clientEmail: 'aisha.qahtani@email.com',
    clientAddress: 'Al Ain, UAE',
    lastUpdated: '2024-04-25T17:30:00Z'
  },

  // TESLA VEHICLES
  {
    id: '6',
    model: 'Tesla Model S',
    year: 2024,
    color: 'Deep Blue Metallic',
    arrivalDate: '2024-06-01',
    status: 'in_stock',
    vinNumber: '5YJSA1E26LF123456',
    currentFloor: 'Showroom 1',
    batteryPercentage: 91,
    pdiCompleted: true,
    pdiTechnician: 'Anna Petrov',
    pdiDate: '2024-06-02',
    pdiNotes: 'Autopilot system calibrated, all features verified',
    brand: 'Tesla',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 105000,
    inShowroom: true,
    showroomEntryDate: '2024-06-03',
    lastUpdated: '2024-06-16T12:00:00Z',
    pdiSystemChecks: [
      {
        system: 'Autopilot',
        status: 'pass',
        notes: 'All sensors calibrated and functioning'
      },
      {
        system: 'Charging System',
        status: 'pass',
        notes: 'Supercharging and home charging tested'
      },
      {
        system: 'Entertainment System',
        status: 'pass',
        notes: 'All streaming services and games working'
      }
    ]
  },
  {
    id: '7',
    model: 'Tesla Model 3',
    year: 2024,
    color: 'Pearl White',
    arrivalDate: '2024-05-28',
    status: 'in_stock',
    vinNumber: '5YJ3E1EA0PF123789',
    currentFloor: 'Showroom 2',
    batteryPercentage: 88,
    pdiCompleted: true,
    pdiTechnician: 'David Chen',
    pdiDate: '2024-05-29',
    pdiNotes: 'Performance model, acceleration tested',
    brand: 'Tesla',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 85000,
    inShowroom: true,
    showroomEntryDate: '2024-05-30',
    lastUpdated: '2024-06-16T15:30:00Z'
  },

  // BYD VEHICLES
  {
    id: '8',
    model: 'BYD Tang EV',
    year: 2024,
    color: 'Crystal White',
    arrivalDate: '2024-05-20',
    status: 'in_stock',
    vinNumber: 'BYD24TG789123456',
    currentFloor: 'Showroom 2',
    batteryPercentage: 88,
    pdiCompleted: true,
    pdiTechnician: 'Hassan Al-Farisi',
    pdiDate: '2024-05-21',
    pdiNotes: 'All-wheel drive system tested, performance excellent',
    brand: 'BYD',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 48000,
    inShowroom: true,
    showroomEntryDate: '2024-05-22',
    lastUpdated: '2024-06-16T10:15:00Z'
  },
  {
    id: '9',
    model: 'BYD Han',
    year: 2024,
    color: 'Aurora Red',
    arrivalDate: '2024-06-05',
    status: 'reserved',
    vinNumber: 'BYD24HN456789123',
    currentFloor: 'New Arrivals',
    batteryPercentage: 92,
    pdiCompleted: false,
    brand: 'BYD',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 52000,
    clientName: 'Fatima Al-Zahra',
    clientPhone: '+971-50-555-7777',
    clientEmail: 'fatima.zahra@email.com',
    clientAddress: 'Dubai Hills, UAE',
    reservedDate: '2024-06-08',
    notes: 'Premium trim package, customer excited about delivery',
    lastUpdated: '2024-06-08T14:20:00Z'
  },

  // NIO VEHICLES
  {
    id: '10',
    model: 'NIO ES8',
    year: 2025,
    color: 'Storm Blue',
    arrivalDate: '2024-06-10',
    status: 'reserved',
    vinNumber: 'NIO25ES8456789123',
    currentFloor: 'New Arrivals',
    batteryPercentage: 75,
    pdiCompleted: false,
    brand: 'NIO',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 95000,
    clientName: 'Mariam Al-Bloushi',
    clientPhone: '+971-50-555-7777',
    clientEmail: 'mariam.bloushi@email.com',
    clientAddress: 'Dubai Hills, UAE',
    reservedDate: '2024-06-12',
    notes: 'Customer reserved before PDI completion, premium trim package',
    lastUpdated: '2024-06-12T16:30:00Z'
  },

  // MERCEDES-BENZ VEHICLES
  {
    id: '11',
    model: 'Mercedes-Benz EQS',
    year: 2024,
    color: 'Obsidian Black',
    arrivalDate: '2024-05-15',
    status: 'in_stock',
    vinNumber: 'W1K2M6C0XNB123456',
    currentFloor: 'Showroom 1',
    batteryPercentage: 89,
    pdiCompleted: true,
    pdiTechnician: 'Klaus Mueller',
    pdiDate: '2024-05-16',
    pdiNotes: 'MBUX system fully configured, luxury features verified',
    brand: 'Mercedes-Benz',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 125000,
    inShowroom: true,
    showroomEntryDate: '2024-05-17',
    lastUpdated: '2024-06-16T11:45:00Z'
  },
  {
    id: '12',
    model: 'Mercedes-Benz S-Class',
    year: 2024,
    color: 'Selenite Grey',
    arrivalDate: '2024-04-20',
    soldDate: '2024-05-10',
    status: 'sold',
    vinNumber: 'W1K3M6C0XNB789012',
    currentFloor: 'Inventory',
    batteryPercentage: 85,
    pdiCompleted: true,
    pdiTechnician: 'Klaus Mueller',
    pdiDate: '2024-04-21',
    pdiNotes: 'Executive package, all luxury features confirmed',
    brand: 'Mercedes-Benz',
    category: 'ICEV',
    customs: 'paid',
    sellingPrice: 180000,
    clientName: 'Sheikh Mohammed Al-Thani',
    clientPhone: '+971-50-999-8888',
    clientEmail: 'mohammed.al-thani@email.com',
    clientAddress: 'Palm Jumeirah, UAE',
    lastUpdated: '2024-05-10T16:00:00Z'
  },

  // BMW VEHICLES
  {
    id: '13',
    model: 'BMW iX',
    year: 2024,
    color: 'Alpine White',
    arrivalDate: '2024-06-01',
    status: 'in_stock',
    vinNumber: 'WBY2Z4C0XNB345678',
    currentFloor: 'Showroom 2',
    batteryPercentage: 93,
    pdiCompleted: true,
    pdiTechnician: 'Hans Weber',
    pdiDate: '2024-06-02',
    pdiNotes: 'iDrive 8 system updated, driving assistance verified',
    brand: 'BMW',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 110000,
    inShowroom: true,
    showroomEntryDate: '2024-06-03',
    lastUpdated: '2024-06-16T13:20:00Z'
  },
  {
    id: '14',
    model: 'BMW M3',
    year: 2024,
    color: 'Isle of Man Green',
    arrivalDate: '2024-05-25',
    status: 'in_stock',
    vinNumber: 'WBS8M9C0XNB567890',
    currentFloor: 'Showroom 1',
    batteryPercentage: 100,
    pdiCompleted: true,
    pdiTechnician: 'Hans Weber',
    pdiDate: '2024-05-26',
    pdiNotes: 'M Performance package verified, track mode tested',
    brand: 'BMW',
    category: 'ICEV',
    customs: 'paid',
    sellingPrice: 95000,
    inShowroom: true,
    showroomEntryDate: '2024-05-27',
    lastUpdated: '2024-06-16T09:15:00Z'
  },

  // AUDI VEHICLES
  {
    id: '15',
    model: 'Audi e-tron GT',
    year: 2024,
    color: 'Daytona Grey',
    arrivalDate: '2024-06-08',
    status: 'in_stock',
    vinNumber: 'WAUZZZ8V0KN123456',
    currentFloor: 'New Arrivals',
    batteryPercentage: 87,
    pdiCompleted: false,
    brand: 'Audi',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 115000,
    notes: 'RS e-tron GT variant, awaiting PDI completion',
    lastUpdated: '2024-06-08T12:00:00Z'
  },

  // PORSCHE VEHICLES
  {
    id: '16',
    model: 'Porsche Taycan',
    year: 2024,
    color: 'Frozen Blue Metallic',
    arrivalDate: '2024-05-30',
    status: 'in_stock',
    vinNumber: 'WP0AB2Y1XNS123456',
    currentFloor: 'Showroom 1',
    batteryPercentage: 90,
    pdiCompleted: true,
    pdiTechnician: 'Michael Schmidt',
    pdiDate: '2024-05-31',
    pdiNotes: 'Turbo S variant, performance systems verified',
    brand: 'Porsche',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 140000,
    inShowroom: true,
    showroomEntryDate: '2024-06-01',
    lastUpdated: '2024-06-16T14:30:00Z'
  },

  // LUCID VEHICLES
  {
    id: '17',
    model: 'Lucid Air',
    year: 2024,
    color: 'Cosmic Silver',
    arrivalDate: '2024-06-12',
    status: 'in_stock',
    vinNumber: 'LUCID123456789012',
    currentFloor: 'New Arrivals',
    batteryPercentage: 95,
    pdiCompleted: false,
    brand: 'Lucid',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 130000,
    notes: 'Dream Edition, awaiting PDI and software setup',
    lastUpdated: '2024-06-12T10:00:00Z'
  },

  // RIVIAN VEHICLES
  {
    id: '18',
    model: 'Rivian R1S',
    year: 2024,
    color: 'Launch Green',
    arrivalDate: '2024-06-05',
    status: 'reserved',
    vinNumber: 'RIVIAN123456789012',
    currentFloor: 'New Arrivals',
    batteryPercentage: 88,
    pdiCompleted: false,
    brand: 'Rivian',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 95000,
    clientName: 'Abdullah Al-Rashid',
    clientPhone: '+971-50-777-9999',
    clientEmail: 'abdullah.rashid@email.com',
    clientAddress: 'Abu Dhabi, UAE',
    reservedDate: '2024-06-07',
    notes: 'Adventure package, customer interested in off-road capabilities',
    lastUpdated: '2024-06-07T15:45:00Z'
  },

  // HYUNDAI VEHICLES
  {
    id: '19',
    model: 'Hyundai IONIQ 5',
    year: 2024,
    color: 'Digital Teal',
    arrivalDate: '2024-05-18',
    status: 'in_stock',
    vinNumber: 'KMHXX00XXXX123456',
    currentFloor: 'Showroom 2',
    batteryPercentage: 91,
    pdiCompleted: true,
    pdiTechnician: 'Park Ji-Sung',
    pdiDate: '2024-05-19',
    pdiNotes: 'V2L feature tested, charging system verified',
    brand: 'Hyundai',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 65000,
    inShowroom: true,
    showroomEntryDate: '2024-05-20',
    lastUpdated: '2024-06-16T16:00:00Z'
  },

  // KIA VEHICLES
  {
    id: '20',
    model: 'Kia EV6',
    year: 2024,
    color: 'Aurora Black',
    arrivalDate: '2024-06-03',
    status: 'in_stock',
    vinNumber: 'KNDJX3XXXX123456',
    currentFloor: 'Showroom 2',
    batteryPercentage: 89,
    pdiCompleted: true,
    pdiTechnician: 'Kim Min-Jae',
    pdiDate: '2024-06-04',
    pdiNotes: 'GT-Line variant, performance features verified',
    brand: 'Kia',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 70000,
    inShowroom: true,
    showroomEntryDate: '2024-06-05',
    lastUpdated: '2024-06-16T17:30:00Z'
  },

  // VOLKSWAGEN VEHICLES
  {
    id: '21',
    model: 'Volkswagen ID.4',
    year: 2024,
    color: 'Moonstone Grey',
    arrivalDate: '2024-05-22',
    status: 'in_stock',
    vinNumber: 'WVWZZZ1KZDW123456',
    currentFloor: 'Showroom 1',
    batteryPercentage: 86,
    pdiCompleted: true,
    pdiTechnician: 'Wolfgang Mueller',
    pdiDate: '2024-05-23',
    pdiNotes: 'ID.4 Pro variant, MEB platform verified',
    brand: 'Volkswagen',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 55000,
    inShowroom: true,
    showroomEntryDate: '2024-05-24',
    lastUpdated: '2024-06-16T18:15:00Z'
  },

  // FORD VEHICLES
  {
    id: '22',
    model: 'Ford Mustang Mach-E',
    year: 2024,
    color: 'Shadow Black',
    arrivalDate: '2024-06-10',
    status: 'in_stock',
    vinNumber: '3FMTK3SU1NMA12345',
    currentFloor: 'New Arrivals',
    batteryPercentage: 92,
    pdiCompleted: false,
    brand: 'Ford',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 75000,
    notes: 'GT Performance Edition, awaiting PDI completion',
    lastUpdated: '2024-06-10T11:30:00Z'
  },

  // CHEVROLET VEHICLES
  {
    id: '23',
    model: 'Chevrolet Bolt EUV',
    year: 2024,
    color: 'Summit White',
    arrivalDate: '2024-05-28',
    status: 'in_stock',
    vinNumber: '1G1FZ6S0XNB123456',
    currentFloor: 'Showroom 2',
    batteryPercentage: 94,
    pdiCompleted: true,
    pdiTechnician: 'Mike Johnson',
    pdiDate: '2024-05-29',
    pdiNotes: 'Premier trim, Super Cruise system verified',
    brand: 'Chevrolet',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 45000,
    inShowroom: true,
    showroomEntryDate: '2024-05-30',
    lastUpdated: '2024-06-16T19:00:00Z'
  },

  // NISSAN VEHICLES
  {
    id: '24',
    model: 'Nissan Ariya',
    year: 2024,
    color: 'Platinum Quartz',
    arrivalDate: '2024-06-08',
    status: 'reserved',
    vinNumber: '5N1AZ0CP0LC123456',
    currentFloor: 'New Arrivals',
    batteryPercentage: 88,
    pdiCompleted: false,
    brand: 'Nissan',
    category: 'EV',
    customs: 'not paid',
    sellingPrice: 58000,
    clientName: 'Yuki Tanaka',
    clientPhone: '+971-50-888-7777',
    clientEmail: 'yuki.tanaka@email.com',
    clientAddress: 'Dubai Silicon Oasis, UAE',
    reservedDate: '2024-06-09',
    notes: 'Premier trim, customer excited about Japanese EV technology',
    lastUpdated: '2024-06-09T13:20:00Z'
  },

  // TOYOTA VEHICLES
  {
    id: '25',
    model: 'Toyota bZ4X',
    year: 2024,
    color: 'Supersonic Red',
    arrivalDate: '2024-06-01',
    status: 'in_stock',
    vinNumber: 'JTDKARFU0N1234567',
    currentFloor: 'Showroom 1',
    batteryPercentage: 90,
    pdiCompleted: true,
    pdiTechnician: 'Takeshi Yamamoto',
    pdiDate: '2024-06-02',
    pdiNotes: 'XLE trim, Toyota Safety Sense verified',
    brand: 'Toyota',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 52000,
    inShowroom: true,
    showroomEntryDate: '2024-06-03',
    lastUpdated: '2024-06-16T20:30:00Z'
  },

  // TEST VEHICLE FOR VIN SCANNER
  {
    id: 'mock-001',
    model: 'Test Vehicle',
    year: 2024,
    color: 'White',
    arrivalDate: '2024-12-21',
    status: 'in_stock',
    vinNumber: 'MOCKVIN000000001',
    currentFloor: 'Inventory',
    batteryPercentage: 85,
    pdiCompleted: false,
    brand: 'Mock',
    category: 'EV',
    customs: 'paid',
    sellingPrice: 50000,
    notes: 'Mock vehicle for testing VIN scanner functionality',
    lastUpdated: '2024-12-21T10:00:00Z'
  }
];
